jobs:
  build-site:
    runs-on: ubuntu-latest
    ...

    - name: blog
      uses: RicardoLSW/blog@master

    ...

    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name == 'push'
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./_site
